### ISSUE TITLE
Cannot open uncrustify.cfg by creating option.

### ISSUE THREAD

**Issue by everLEEst** [LaurentTreguier/vscode-uncrustify#11] opened 2017-07-22 16:59 UTC
after creating uncrustify.cfg by uncrustify.create,
If I try to open the file, it always failed with 'Cannot read property 'tag' of undefined.'

**Comment by LaurentTreguier** [comment] 2017-07-22 17:15
Looks awfully similar to #9... 
What are the contents of uncrustify.cfg? Is it created correctly?

**Comment by LaurentTreguier** [comment] 2017-07-24 15:50
I think it should be fixed now. But I could be wrong, so please re-open if it's not the case.

**Comment by everLEEst** [comment] 2017-07-24 16:43
yeah let me check it tomorrow.
thanks a lot for fast resolve :) 👍 
by the way, have you any plan to apply range formatting feature?
It only needs really few code changes with using '--frag' option in uncrustify,
and actually I locally modify the feature and it works well with block selections.
If you don't mind I could just contribute my code as well.

**Comment by LaurentTreguier** [comment] 2017-07-24 16:44
Why not ? I simply didn't know Uncrustify had this option. Has it always been there or is it only past a certain version ?

**Comment by everLEEst** [comment] 2017-07-24 16:50
ftp://history.knowsley.gov.uk/hpux/Development/Tools/uncrustify-0.60/uncrustify-0.60.man.html
at least the link said the option was exist in 2009,
and my opensource project formatting rule is really something special even powerful uncrustify cannot supporting them fully, so I generally use some modified version based in 2014, and it works well in that version though.
But yeah they have really weak documents so hardly find the way of using it.
my project don't allow rewrite code for formatting which can be changed git author, so I need range format option and I find that these option can be useful :)

**Comment by GijsGoudzwaard** [comment] 2017-11-01 14:51
I'm having the same issue. Everytime I click on uncrustify.cfg it gives the error `Unable to open 'Uncrustify configuration': Cannot read property 'tag' of undefined.`   The uncrustify.cfg is generated by using uncrustify.create

This issue should be reopened

**Comment by LaurentTreguier** [comment] 2017-11-01 16:14
I have had this issue as well when I last worked on this extension... I'll try to see where it comes from. In the meantime, simply re-creating the file can fix it, sometimes it doesn't work and sometimes it does work.

**Comment by GijsGoudzwaard** [comment] 2017-11-01 16:25
I recreated the file like 5 times in a row and it didn't work any of the 5 times

**Comment by GijsGoudzwaard** [comment] 2017-11-01 16:28
When I open the file in vim it is empty, maybe the problem is that it doesn't setup the file correctly?

**Comment by LaurentTreguier** [comment] 2017-11-01 18:16
Yes, the problem is that the file is not written properly. But it's random, sometimes it works for me...
You can manually create the file with `uncrustify --update-config-with-doc > uncrustify.cfg` for now. If that doesn't work...

**Comment by GijsGoudzwaard** [comment] 2017-11-01 18:29
Your command didn't work, using this command `uncrustify --update-config-with-doc -c uncrustify.cfg > uncrustify.cfg` did work for me.

**Comment by LaurentTreguier** [comment] 2017-11-01 18:29
Ok, what version of uncrustify do you have ?

**Comment by GijsGoudzwaard** [comment] 2017-11-01 18:30
v0.59

**Comment by LaurentTreguier** [comment] 2017-11-01 18:35
So this version simply needs an original config file with newer versions don't... Creating an empty file first and then filling it (just like you did) works with any version, so I guess this is how I should handle it.

**Comment by LaurentTreguier** [comment] 2017-11-01 19:08
Hopefully this won't need to be re-opened again

**Closed as completed** 2017-11-01 19:07 UTC
